require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5.0

# ================ Style ===============
# TODO: Activate later
Style/Documentation:
  Enabled: false

# ================ LAYOUT ==============
Layout/LineLength:
  Max: 150

# ================ LINT ================
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb

# ================ Metics ================
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - snfoil.gemspec

# ================ RSPEC ================
RSpec/FilePath:
  CustomTransform:
    SnFoil: snfoil
    CRUD: crud

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SubjectStub:
  Enabled: false