name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.0,3.2,3.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: limited-effort/snfoil-policy:${{ matrix.ruby-version }}-test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            RUBY_VERSION=${{ matrix.ruby-version }}

      - name: Run Rubocop
        run: docker run --rm limited-effort/snfoil-policy:${{ matrix.ruby-version }}-test bundle exec rubocop

      - name: Run Fasterer
        run: docker run --rm limited-effort/snfoil-policy:${{ matrix.ruby-version }}-test bundle exec fasterer

      - name: Run Bundle Audit
        run: docker run --rm limited-effort/snfoil-policy:${{ matrix.ruby-version }}-test bundle exec bundle audit check --update

      - name: Run RSpec
        run: docker run --rm limited-effort/snfoil-policy:${{ matrix.ruby-version }}-test bundle exec rspec